### ISSUE TITLE
<subgroup3 고객챌린지-UserInterface>

### ISSUE THREAD

**Issue by Jwaminju** [idealization/software-engineering#4]
1. main page서 추천 책 목록 종류 3개에서 6개로?
 --> 기존) 추천 알고리즘 3개에 의한 것
--> 수정 후) 추천 알고리즘 3개 + 신간(MD 추천)/베스트셀러/나이대별추천 
     --> 만약 6개 카데고리로 넣는다면 추가한 3개 카테고리에서도 뺴고도 화살표 버튼을 넣을 것인지?( 몇개만 보여줄지 책을 넘기면서 볼 수 있게 할것인지?  )

![image](https://user-images.githubusercontent.com/49024958/114798887-64cfd580-9dd1-11eb-9147-8d12ede4d499.png)

**Comment by idealization** [comment]
나는 넷플릭스처럼 조금 난잡하게 카테고리를 많이 해도 괜찮을 것 같아!
어차피 책 표지만 보여주는 거라 오히려 정신 없다 ~ 보단 추천이 풍부하다고 느낄 것 같아서!!
고객이 뉴비면 추천할 게 없기두 하고..

**Comment by Heeming** [comment]
나이대는 넣는다 해도 나머지 2개는 굳이 안 넣어도 될 것 같아요. 개인 기록을 바탕으로 한 추천이 아니다 보니 그냥 나눠도 괜찮을 듯.
